backport basic refactor from PR#100
TuringLang/Libtask.jl pull request #103
Opened 2022-01-05 00:55 UTC by KDr2

Besides adding `TapeInstruction`, I did a little code refactor in https://github.com/TuringLang/Libtask.jl/pull/100, and I'd like to move that refactor onto master branch before doing benchmark and performance optimization.

2022-01-05 00:59 UTC, KDr2 commented
It mainly did two things:
- Moved instruction counter from task to tape.
- Optimized the code structure of task copying.

2022-01-05 10:33 UTC, yebai requested changes

2022-01-05 10:33 UTC, yebai commented on src/tapedfunction.jl
> +    tape::Vector{AbstractInstruction}
```suggestion
    tape::Vector{<:AbstractInstruction}
```

2022-01-05 10:33 UTC, yebai commented on src/tapedfunction.jl
> +    tape::Vector{AbstractInstruction}
Using abstract types in structs/containers have performance penalties.

2022-01-05 10:33 UTC, yebai commented on src/tapedfunction.jl
> +any_box(x::Box) = Box{Any}(x.val)
I suggest that we use `Box{Any}` to replace all `any_box` use cases and remove `any_box` to reduce redundancy.

2022-01-05 10:33 UTC, yebai commented on src/tapedfunction.jl
> +        tape.counter += 1
```suggestion
       increase_counter(tape)
```

2022-01-05 10:33 UTC, yebai commented on src/tapedtask.jl
> +    new_data = Vector{AbstractInstruction}()
Consider avoiding using container types with abstract types to improve type stability.

2022-01-05 10:37 UTC, yebai commented
@phipsgabler @devmotion we are now entering the performance and design optimisation and phase of the tape mechanism since the functionality has been proven correct. Please comment on any issues so that we can gradually build a lightweight, performant, maintainable tape implementation. The tape implementation will be moved into `Tapir` later when it is more mature.

2022-01-05 11:13 UTC, KDr2 commented on src/tapedfunction.jl
> +    tape::Vector{AbstractInstruction}
updated.

2022-01-05 11:13 UTC, KDr2 commented on src/tapedfunction.jl
> +any_box(x::Box) = Box{Any}(x.val)
updated.

2022-01-05 11:13 UTC, KDr2 commented on src/tapedfunction.jl
> +        tape.counter += 1
updated.

2022-01-05 11:14 UTC, KDr2 commented on src/tapedtask.jl
> +    new_data = Vector{AbstractInstruction}()
I will benchmark this and try to figure out a way to avoid this in the performance task.

2022-01-05 12:50 UTC, yebai approved these changes

2022-01-05 14:10 UTC, phipsgabler commented on src/tapedfunction.jl
> +mutable struct Instruction{F} <: AbstractInstruction
Why does this need to be mutable? Is `owner` set after construction in some cases?

2022-01-05 14:10 UTC, phipsgabler commented on src/tapedfunction.jl
> +end
```suggestion
function increase_counter!(t::Tape)
    t.counter > length(t) && return
    # instr = t[t.counter]
    t.counter += 1
    return t
end
```

2022-01-05 14:10 UTC, phipsgabler commented on src/tapedfunction.jl
>  end
Intuitively, I'd have expected this to also return the result of the function. Or is that extracted in another place?

2022-01-05 14:10 UTC, phipsgabler commented on src/tapedfunction.jl
> +end
```suggestion
function setowner!(tape::Tape, owner)
    tape.owner = owner
    return tape
end
```

2022-01-05 14:10 UTC, phipsgabler commented on src/tapedfunction.jl
>      buf = IOBuffer()
Why the extra buffer? You could directly `println` to `io`.

2022-01-05 14:10 UTC, phipsgabler commented on src/tapedtask.jl
>      exc
```suggestion
    exc::Exception
```

2022-01-05 19:47 UTC, KDr2 commented on src/tapedfunction.jl
>  end
The result is stored in `Instruction.output`.

2022-01-05 19:54 UTC, KDr2 commented on src/tapedfunction.jl
>      buf = IOBuffer()
Here I use an extra buffer, because that there are too many calls to `println` with `io` (which is `stdout` in most situations). And between these calls, the current task may be switched off, then Juia does some `print` in another task, and then switched on. In that case, the output will not be continuous and that makes it annoying to read.

2022-01-05 19:57 UTC, KDr2 commented on src/tapedtask.jl
>      exc
updated.

2022-01-05 19:57 UTC, KDr2 commented on src/tapedfunction.jl
> +end
updated.

2022-01-05 19:57 UTC, KDr2 commented on src/tapedfunction.jl
> +end
updated.

2022-01-05 19:58 UTC, KDr2 commented on src/tapedfunction.jl
> +mutable struct Instruction{F} <: AbstractInstruction
Yes.

2022-01-06 10:26 UTC, merged

2022-01-08 09:44 UTC, phipsgabler commented on src/tapedfunction.jl
>      buf = IOBuffer()
Good reason. Then put a comment there to remind future readers why this should not be refactored.