[WIP] Performance and Benchmarks
TuringLang/Libtask.jl pull request #104
Opened 2022-01-07 05:47 UTC by KDr2

2022-01-07 08:16 UTC, KDr2 commented
It's interesting, in the last commit I found `step_in` a tape is faster than running a model directly, maybe I missed something?
```
$ julia --project perf/p0.jl
  2.286 μs (38 allocations: 1.95 KiB)
  97.440 ns (1 allocation: 48 bytes)
  440.273 μs (48 allocations: 2.56 KiB)
  969.364 ns (4 allocations: 288 bytes)
```

2022-01-07 11:47 UTC, yebai commented
It is possible that `step_in` the tape executes faster than the original function `f(args...)` since the tape specialises more (e.g. removing control flows, caching input/output arguments). Note that the total runtime (of Turing inference algorithm) also depends on the `CTask` constructor:

```julia
julia> @btime t = Libtask.CTask(f, args...);
  258.923 ms (766345 allocations: 43.38 MiB)

julia> @btime Libtask.step_in(t.tf.tape, args)
  95.054 ns (1 allocation: 48 bytes)

julia> @btime f(args...)
  2.549 μs (38 allocations: 1.95 KiB)
(2.0, VarInfo (2 variables (μ, σ), dimension 2; logp: -1.2750123006e7))

```

So it appears that a lot of time is spent on repetitively constructing `CTask`. Maybe we can speed this up by resuing tapes?

2022-01-09 07:32 UTC, KDr2 commented
### Without Cache:
```
$ julia --project perf/p0.jl
"Directly call..." = "Directly call..."
  2.233 μs (38 allocations: 1.95 KiB)
"CTask construction..." = "CTask construction..."
  410.719 ms (974878 allocations: 59.77 MiB)
"Step in a tape..." = "Step in a tape..."
  90.543 ns (1 allocation: 48 bytes)
"Directly call..." = "Directly call..."
  422.273 μs (48 allocations: 2.56 KiB)
"CTask construction..." = "CTask construction..."
  416.812 ms (974908 allocations: 59.77 MiB)
"Step in a tape..." = "Step in a tape..."
  923.559 ns (4 allocations: 288 bytes)
```


### With IR and Tape Cache:
```
$ julia --project perf/p0.jl
"Directly call..." = "Directly call..."
  2.117 μs (38 allocations: 1.95 KiB)
"CTask construction..." = "CTask construction..."
  99.222 μs (489 allocations: 22.02 KiB)
"Step in a tape..." = "Step in a tape..."
  87.400 ns (1 allocation: 48 bytes)
"Directly call..." = "Directly call..."
  417.133 μs (48 allocations: 2.56 KiB)
"CTask construction..." = "CTask construction..."
  103.745 μs (495 allocations: 22.48 KiB)
"Step in a tape..." = "Step in a tape..."
  924.314 ns (4 allocations: 288 bytes)
```

2022-01-11 07:51 UTC, KDr2 commented
In spite of numeric test failures and a few errors, unit tests finished in about 2 hours on my machine:

```
real    130m46.448s
user    126m4.793s
sys     5m25.685s
```

2022-01-11 13:48 UTC, yebai requested changes

2022-01-11 13:48 UTC, yebai commented on src/tapedtask.jl
>      tf.owner != nothing && error("TapedFunction is owned to another task.")
```suggestion
    tf.owner != nothing && error("TapedFunction is owned by another task.")
```

2022-01-11 13:48 UTC, yebai commented on src/tapedtask.jl
> +            reset!(tf, ir, copy(tape, Dict{UInt64, Any}(); partial=false))
We need to update the `args` stored in `tf::Tape` when using cached tape.

2022-01-11 13:50 UTC, yebai commented on Project.toml
> +Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Consider moving these additional dependencies into `perf/Project.toml`

2022-01-11 13:55 UTC, yebai commented on src/tapedtask.jl
> +            ir, tape = TRCache[tf.func]
We need to cache by call signature, i.e. `TRCache[(tf.func, typeof.(args)...)]` to avoid incorrect function dispatching.

2022-01-12 07:37 UTC, devmotion commented on perf/p0.jl
> +@model gdemo(x, y) = begin
DynamicPPL contains a set of test models, maybe they can be used?

2022-01-12 07:37 UTC, devmotion commented on src/tapedtask.jl
> +    tf.owner != nothing && error("TapedFunction is owned by another task.")
```suggestion
    tf.owner !== nothing && error("TapedFunction is owned by another task.")
```

2022-01-12 12:50 UTC, yebai commented on perf/p0.jl
> +@model gdemo(x, y) = begin
@devmotion  DynamicPPL test [models](https://github.com/TuringLang/DynamicPPL.jl/blob/master/src/test_utils.jl) doesn't currently include `gdemo`. On the other hand, it is useful to have a complete MWE here to test the efficiency and correctness of Libtask.

2022-01-12 12:52 UTC, yebai commented on perf/src/LibtaskPerf.jl
> +module LibtaskPerf
@KDr2 Why do we need this empty package? If it is for `Project.toml`, maybe we can explicitly call `activate perf` to avoid this dummy package.

2022-01-12 12:53 UTC, yebai approved these changes
I can confirm that the tests now run correctly - we can rerun the Turing CI once this PR is merged. Fingers crossed!

2022-01-13 00:00 UTC, KDr2 commented on perf/src/LibtaskPerf.jl
> +module LibtaskPerf
Removed  :D

2022-01-18 08:03 UTC, yebai commented on perf/p2.jl
> +using Turing, Test, AbstractMCMC, DynamicPPL, Random, Turing.RandomMeasures, Libtask
@KDr2 Maybe write a `perf/run.jl` script to run all these examples on CI. They also serve as additional integration tests, apart from benchmarking purposes.

2022-01-18 08:04 UTC, yebai commented on src/tapedfunction.jl
> +mutable struct NewInstruction <: AbstractInstruction
Can you add some docstring/comment explaining why a special `NewInstruction` is needed?

2022-01-18 08:05 UTC, yebai commented on src/tapedfunction.jl
> +    try
```suggestion
    # Catch run-time exceptions / errors.
    try
```

2022-01-18 08:07 UTC, yebai commented on src/tapedfunction.jl
> +        expr = Expr(:new, map(val, instr.input)...)
This is probably going to cause performance issues as we repeatedly parse and eval AST expressions at run-time. Maybe re-write as a generated function?

2022-01-18 08:14 UTC, yebai commented on src/tapedfunction.jl
> +    ins = NewInstruction(args, output, tape)
Similiar, since we know the type of `output`, can we replace the new operator with an explicit constructor (e.g. `Array{Int}(3)`).

2022-01-18 08:36 UTC, KDr2 commented on src/tapedfunction.jl
> +    ins = NewInstruction(args, output, tape)
Unfortunately we can't do that, if there's a `new` operator, it indicates the default constructor we need is hidden by an inner constructor, use a `new` expression to access it is the only way I found.

2022-01-18 08:42 UTC, KDr2 commented on src/tapedfunction.jl
> +mutable struct NewInstruction <: AbstractInstruction
updated.

2022-01-18 08:42 UTC, KDr2 commented on src/tapedfunction.jl
> +    try
updated.

2022-01-18 12:34 UTC, rikhuijzer commented on src/tapedfunction.jl
> +    ins = NewInstruction(args, output, tape)
Maybe I misunderstand, but the `NewInstruction` is an intermediate struct to create an `Instruction`? Just to be sure that the default way of handling this isn't overlooked, this is how structs are normally constructed when an inner constructor hides the default constructor:

```julia
struct A
    b::String

    function A(b::Float64)
        return string(b)
    end
end

A(b::Int) = A(Float64(b))

A(1.0) # "1.0"

A(1) # "1.0"
```

Apologies if I misunderstood the problem; feel free to ignore my comment then

2022-01-18 14:04 UTC, KDr2 commented on src/tapedfunction.jl
> +    ins = NewInstruction(args, output, tape)
@rikhuijzer you are right, this is exactly the problem, we cant create an A with `A("1")`, but we can do `eval(Expr(:new, A, "string"))`.

2022-01-19 00:47 UTC, KDr2 commented
This PR is ready to merge. @yebai

2022-01-19 00:47 UTC, KDr2 commented on perf/p2.jl
> +using Turing, Test, AbstractMCMC, DynamicPPL, Random, Turing.RandomMeasures, Libtask
Done.

2022-01-19 09:40 UTC, yebai approved these changes

2022-01-19 09:41 UTC, merged