Control flow support
TuringLang/Libtask.jl pull request #107
Opened 2022-01-23 02:26 UTC by KDr2

Implement https://github.com/TuringLang/Libtask.jl/issues/96.

2022-01-23 10:57 UTC, phipsgabler commented on src/tapedfunction.jl
> +    condition::Any
I think this can only be a variable id or `nothing`.

2022-01-23 10:57 UTC, phipsgabler commented on src/tapedfunction.jl
> +    block_map::Dict{Int, Int}
Just trying to understand the representation...

You are storing the block structure by saving all instructions linearly, and then additionally in `block_map` the mapping from block number to the id of the "block instruction" on top of a block, do I get this right? So

```
1 ─ %1 = x > 1
└──      goto #3 if not %1
2 ─ %3 = Main.rand()
└──      return %3
3 ─      return 2
```

would become, e.g.

```
1 => Block(1, x)
2 => %1 = x > 1
3 => goto 3 if not %1
4 => Block(2)
5 => %3 = Main.rand()
6 => return %3
```

with `block_map = Dict(1 => 1, 2 => 4)`?

2022-01-23 11:31 UTC, KDr2 commented on src/tapedfunction.jl
> +    block_map::Dict{Int, Int}
Yes, you are right. We only have the id of a `Block` in the `BranchInstruction`, but we don't its index (where is it on the tape). With this map, we can easily find where a Branch wants to go without iterating the whole tape.

2022-01-24 01:55 UTC, KDr2 commented on src/tapedfunction.jl
> +    condition::Any
A `Box` or `nothing` 😄

2022-01-24 07:22 UTC, rikhuijzer reviewed
The integration tests of #106 and #109 are not enabled for this PR which can be seen by looking at the running time for the integration tests. Running all tests takes longer than 1 minute.

2022-01-24 12:05 UTC, phipsgabler commented on src/tapedfunction.jl
> +    condition::Any
Any reason not to use a `Union` then, if only for documentation purposes?

2022-01-24 12:45 UTC, KDr2 commented on src/tapedfunction.jl
> +    condition::Any
Updated.

2022-01-24 12:46 UTC, KDr2 commented
Oh my, who deleted the master branch? 🤕

2022-01-24 13:15 UTC, yebai commented
> Oh my, who deleted the master branch? 🤕

Fixed - it was deleted by `merge-bot` because I merged a PR from `master` to this PR. I also added protection so this won't happen in the future.

2022-01-25 14:34 UTC, KDr2 commented on src/tapedfunction.jl
> +    block::Int
```suggestion
    block_id::Int
```

2022-01-25 14:34 UTC, KDr2 commented on src/tapedfunction.jl
> +    id::Int
```suggestion
    block_id::Int
```

2022-01-25 14:35 UTC, KDr2 commented on src/tapedfunction.jl
> +    condition::Union{Bool, Box{Any}, Nothing}
use false for nothing, remove `Nothing`

2022-01-25 14:49 UTC, KDr2 commented on src/tapedfunction.jl
> +                    _box(br.condition), br.block, map(_box, br.args), taped)
use false if br.condition is nothing.

2022-01-25 14:56 UTC, phipsgabler commented on src/tapedfunction.jl
> +    block_map::Dict{Int, Int}
OK cool. Can you add couple of comments somewhere about that? Or is there some kind of developer documentation elsewhere?

2022-01-25 14:57 UTC, KDr2 commented on src/tapedfunction.jl
> +function init!(tf::TapedFunction, args)
move this into the inner constructor.

2022-01-25 15:06 UTC, KDr2 commented on src/tapedfunction.jl
>  function reset!(tf::TapedFunction, ir::IRTools.IR, tape::RawTape)
make this a constructor.

2022-01-25 15:13 UTC, KDr2 commented on src/tapedtask.jl
> +    func = copy_box(x.func, roster)
add a comment

2022-01-26 10:35 UTC, yebai requested changes
Many thanks @KDr2 - I took another careful look. See below for comments.

2022-01-26 10:35 UTC, yebai commented on src/tapedfunction.jl
>      ir::Union{Nothing, IRTools.IR}
I think Julia allows us to leave fields of structs as `#undef`. Maybe we can let `ir` be `#undef` to replace `nothing`. Then, we can replace `Union{Nothing, IRTools.IR}` with `IRTools.IR`.

2022-01-26 10:35 UTC, yebai commented on src/tapedfunction.jl
> +val(x::GlobalRef) = getproperty(x.mod, x.name)
Nice improvements!

2022-01-26 10:35 UTC, yebai commented on src/tapedfunction.jl
> +arg_boxer(var, boxes) = var
```suggestion
arg_boxer(var, boxes::Dict) = var
```

2022-01-26 10:35 UTC, yebai commented on src/tapedfunction.jl
> +arg_boxer(var::IRTools.Variable, boxes) = get!(boxes, var, Box{Any}(nothing))
```suggestion
arg_boxer(var::IRTools.Variable, boxes::Dict) = get!(boxes, var, Box{Any}(nothing))
```

2022-01-26 10:35 UTC, yebai commented on src/tapedfunction.jl
> +                @warn "Unknown IR code: " st
I think we should error here so that user knows something went wrong. 
```suggestion
                @error "Unknown IR code: " st
```

2022-01-26 10:35 UTC, yebai commented on src/tapedtask.jl
> +function TapedTask(f, args...)
Let’s keep this comment for future reference. 
```suggestion
# NOTE: evaluating model without a trace, see
 # https://github.com/TuringLang/Turing.jl/pull/1757#diff-8d16dd13c316055e55f300cd24294bb2f73f46cbcb5a481f8936ff56939da7ceR329
function TapedTask(f, args...)
```

2022-01-26 10:35 UTC, yebai commented on src/tapedtask.jl
> +    if haskey(TRCache, cache_key)
Let’s perhaps move this caching logic into `TapeFunction` constructor. Apologies for the confusion in our meeting. After some thought, I feel this fits better in `tapedfunction.jl`.

2022-01-26 10:35 UTC, yebai commented on src/tapedtask.jl
> +        TRCache[cache_key] = tf
We no longer need this if we cache `tapedfunction` by default.

2022-01-26 10:35 UTC, yebai commented on src/tapedtask.jl
>  function step_in(tf::TapedFunction, args)
I feel we can merge `step_in` with `(tf::FapedFunction)(args)` by adding a callback function, e.g. 

```julia

function (tf::TapedFunction)(args...; callback=nothing)
     # run the raw tape
     if length(args) > 0
         input = map(box, args)
         tf.tape[1].input = input
     end
     tf.counter = 1
     while true
         ins = tf[tf.counter]
         ins()

        callback isa nothing || callback() # we can wrap the produce and wait code into this callback function. 
         isa(ins, ReturnInstruction) && break
     end
     return result(tf)
 end

```

2022-01-26 10:35 UTC, yebai commented on src/tapedtask.jl
> +    new_data = RawTape(undef, length(old_data))
Maybe use `new_tape` and `old_tape` for better clarity? 
```suggestion
    new_tape = RawTape(undef, length(old_data))
```

2022-01-26 10:35 UTC, yebai commented on src/tapedtask.jl
>  function Base.copy(tf::TapedFunction)
Maybe these `copy` functions for `Instruciton`/`TapedFunction`/`RawTape` should probably be moved to the `tapedfunciton.jl` file.

2022-01-27 08:40 UTC, yebai approved these changes

2022-01-27 08:40 UTC, merged