Switch from IRTools to CodeInfo
TuringLang/Libtask.jl pull request #126
Opened 2022-02-23 11:15 UTC by KDr2

Fix https://github.com/TuringLang/Libtask.jl/issues/117

2022-02-23 11:37 UTC, KDr2 commented
It turns out `CodeInfo` differs **REALLY A LOT** between versions...

2022-02-23 11:44 UTC, yebai commented
> It turns out CodeInfo differs REALLY A LOT between versions...

Let's focus on Julia `>=1.7` in this PR.

2022-02-23 11:46 UTC, KDr2 commented
Take function `g` below as an exmaple:
```
function g(x, y)
  if x>y
    r= string(sin(x))
  else
    r= sin(x) * cos(y)
  end
  return r
end
```

Its `CodeInfo` under 1.6:
```
 :(Base.slt_int(_3, _2))
 :(goto %7 if not %1)
 :(Base.sitofp(Float64, _2))
 :($(Expr(:invoke, MethodInstance for sin(::Float64), :(Base.Math.sin), :(%3))))
 :($(Expr(:invoke, MethodInstance for string(::Float64), :(Main.string), :(%4))))
 :(goto %12)
 :(Base.sitofp(Float64, _2))
 :($(Expr(:invoke, MethodInstance for sin(::Float64), :(Base.Math.sin), :(%7))))
 :(Base.sitofp(Float64, _3))
 :($(Expr(:invoke, MethodInstance for cos(::Float64), :(Base.Math.cos), :(%9))))
 :(Base.mul_float(%8, %10))
 :(φ (%6 => %5, %11 => %11))
 :(return %12)
```

Under 1.7
```
 Core.NewvarNode(:(_4))
 :(_2 > _3)
 :(goto %7 if not %2)
 :(Main.sin(_2))
 :(_4 = Main.string(%4))
 :(goto %10)
 :(Main.sin(_2))
 :(Main.cos(_3))
 :(_4 = %7 * %8)
 :(return _4)
```

Under 1.8:
`CodeInfoToosl.jl` throws en error while getting its `CodeInfo`, code fetched by `@code_lwoered`:

```
julia> @code_lowered g(1.,2.)
CodeInfo(
1 ─      Core.NewvarNode(:(r))
│   %2 = x > y
└──      goto #3 if not %2
2 ─ %4 = Main.sin(x)
│        r = Main.string(%4)
└──      goto #4
3 ─ %7 = Main.sin(x)
│   %8 = Main.cos(y)
└──      r = %7 * %8
4 ┄      return r
)
```

Conclusion: 
- `CodeInfo` changed a lot between v1.6 and v1.7
- `CodeInfoTools.jl` doesn't work on v1.8

2022-02-23 11:52 UTC, yebai commented
> CodeInfo changed a lot between v1.6 and v1.7

Good to know,  probably due to the major compiler refactoring in 1.7.

> CodeInfoTools.jl doesn't work on v1.8

Maybe raise an issue on the `CodeInfoTools` package, or help fix it if not major?

2022-02-23 11:53 UTC, KDr2 commented
Maybe we can remove the dependency of `CodeInfoTools.jl` too, all we want is to get the `CodeInfo` yet, but not to update the `CodeInfo`, so maybe there's a simple way to do that.

2022-02-23 12:00 UTC, yebai commented
> Maybe we can remove the dependency of CodeInfoTools.jl too, all we want is to get the CodeInfo yet, but not to update the CodeInfo, so maybe there's a simple way to do that.

We will likely need to update `CodeInfo` in the future, e.g. when we inline all the instructions. So we will probably build up a set of utilities for manipulating `CodeInfo`, which will be similar to `CodeInfoTools`. If that's the case, it might be better to depend on `CodeInfoTools` and help to improve it. 

I took a quick look at the 1.8 erro, and itt appears that Julia has a simple function signature change between 1.7 and 1.8. It should be possible to fix that quickly.

2022-02-23 12:02 UTC, yebai commented
CC @femtomc

2022-02-23 12:29 UTC, devmotion commented on Project.toml
> +MacroTools = "0.5"
It was an indirect dependency of IRTools anyway but now that it is removed - could MacroTools be removed?

2022-02-23 12:29 UTC, devmotion commented on Project.toml
> +julia = "1.6"
The automerge guidelines demand that the version is bumped to 0.8.0 if the Julia compat is narrowed: Patch releases are not allowed to do that (https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/#New-versions-of-existing-packages).

2022-02-23 12:29 UTC, devmotion commented on src/tapedfunction.jl
> +            ir = code_inferred(tf.func, typeof.(args)...)
Simpler and without potentially slow broadcasting and splatting:
```suggestion
            ir = code_inferred(tf.func, typeof(args))
```
(One can provide the type of the arguments also as a `Tuple{T1,T2,...}`).

2022-02-23 12:29 UTC, devmotion commented on src/tapedfunction.jl
> +box_any(id::Symbol, x) = Box{Any}(id, x)
Couldn't you just define a single argument outer constructor?
```suggestion
Box(x) = Box(gensym(), x)
Box{T}(x) where {T} = Box{T}(gensym(), x)
```
?

2022-02-23 12:29 UTC, devmotion commented on src/tapedfunction.jl
> +    @error "None box found for slot" slot
Maybe this should be an actual `error`?

2022-02-23 13:12 UTC, femtomc commented
Re — open issue in CodeInfoTools with stacktrace for failure on > 1.8.

2022-02-23 13:24 UTC, KDr2 commented
> Re — open issue in CodeInfoTools with stacktrace for failure on > 1.8.

I opened 2 related isssus:
- https://github.com/JuliaCompilerPlugins/CodeInfoTools.jl/issues/13
- https://github.com/JuliaCompilerPlugins/CodeInfoTools.jl/issues/12

2022-02-23 13:35 UTC, KDr2 commented on Project.toml
> +MacroTools = "0.5"
`MacroTools.@forward` is still in use.

2022-02-23 13:41 UTC, devmotion commented on Project.toml
> +MacroTools = "0.5"
If this is the only place where it is used it will be easy to remove it in a subsequent PR :slightly_smiling_face:

2022-02-23 13:49 UTC, KDr2 commented on Project.toml
> +MacroTools = "0.5"
I created an issue: https://github.com/TuringLang/Libtask.jl/issues/127

2022-02-23 14:54 UTC, KDr2 commented
All tests passed with https://github.com/JuliaCompilerPlugins/CodeInfoTools.jl/pull/14.

2022-02-23 17:10 UTC, femtomc commented
Re — inlining transforms should likely not live in CodeInfoTools. Ideally, the plugin (speculative) interface should be used to do this. It’s still WIP tho.

also, tracking types and things that are required to do inlining is possible in CodeInfoTools (just like IRTools) but there’s no really code to do that yet

2022-02-24 06:29 UTC, rikhuijzer commented
The tests currently fail on the Turing test suite with the following errors (maybe more)

```
┌ Error: Unknown IR code:
│   typeof(line) = Core.SlotNumber
│   line = :(_28)
└ @ Libtask ~/git/Libtask.jl/src/tapedfunction.jl:291
```
and
```
dynamic model: Error During Test at /home/rik/git/Turing.jl/test/test_utils/staging.jl:42
  Got exception outside of a @test
  MethodError: no method matching iterate(::Nothing)
  Closest candidates are:
    iterate(::Union{LinRange, StepRangeLen}) at /nix/store/y46fn31jpgwkzj6hi1xjv0246x5w5dig-julia-bin-1.7.2/share/julia/base/range.jl:826
    iterate(::Union{LinRange, StepRangeLen}, ::Integer) at /nix/store/y46fn31jpgwkzj6hi1xjv0246x5w5dig-julia-bin-1.7.2/share/julia/base/range.jl:826
    iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at /nix/store/y46fn31jpgwkzj6hi1xjv0246x5w5dig-julia-bin-1.7.2/share/julia/base/dict.jl:695
    ...
  Stacktrace:
    [1] consume(ttask::TapedTask{var"#imm#31"})
      @ Libtask ~/git/Libtask.jl/src/tapedtask.jl:144
```

2022-02-24 15:27 UTC, KDr2 commented
> The tests currently fail on the Turing test suite with the following errors (maybe more)

Hope https://github.com/TuringLang/Libtask.jl/pull/126/commits/2e9694087b61865bd745855e9f6cb5f84d28738a fixes them.

2022-02-24 16:11 UTC, yebai commented
Many thanks, @femtomc would you like to make a release of `CodeInfoTools` so that tests can pass here?

2022-02-24 16:15 UTC, devmotion commented
> PS: Why our IntegrationTest doesn't show the errors?

Because Turing is not compatible with Libtask 0.7 or 0.8, and hence it is not possible to run them:
https://github.com/TuringLang/Libtask.jl/runs/5321568590?check_suite_focus=true#step:6:18

2022-02-24 16:27 UTC, rikhuijzer commented
> Because Turing is not compatible with Libtask 0.7 or 0.8, and hence it is not possible to run them:
> https://github.com/TuringLang/Libtask.jl/runs/5321568590?check_suite_focus=true#step:6:18

We could add a bit of logic to the CI which removes the compat entry from Turing for these integration tests? Would require only a few lines of code. Ping me if I need to open a PR for this on this repo.

2022-02-24 16:32 UTC, yebai commented
> We could add a bit of logic to the CI which removes the compat entry from Turing for these integration tests? Would require only a few lines of code. Ping me if I need to open a PR for this on this repo.

Seconded - that would be nice! @rikhuijzer

2022-02-24 16:49 UTC, devmotion commented
> We could add a bit of logic to the CI which removes the compat entry from Turing for these integration tests? Would require only a few lines of code. Ping me if I need to open a PR for this on this repo.

I think we shouldn't do this. The point of breaking releases is to mark that there are breaking changes - so one can't expect downstream packages to work. And if downstream packages are broken it's not an issue since they explicitly state that they might not be compatible with this breaking release and also the package manager will never install them before the compat bound is updated.

2022-02-24 16:51 UTC, devmotion commented
And if you are about to make a breaking release you can already now only bump the version in the final commit before the PR is merged - then the downstream packages will be tested and you will see test errors. In this PR the issue is that Turing is not even compatible with Libtask 0.7 though.

2022-02-24 21:09 UTC, yebai commented on Project.toml
> +version = "0.8.0"
Let's change this version later so the integration tests can run. 
```suggestion
version = "0.7.0"
```

2022-02-25 07:26 UTC, rikhuijzer commented on src/tapedfunction.jl
> +        if isa(line, Core.NewvarNode)
Shouldn't this be dispatches on type?

2022-02-25 07:28 UTC, rikhuijzer commented on src/tapedfunction.jl
> +            f = args[1]
```suggestion
            func = args[1]
```

2022-02-25 07:40 UTC, KDr2 commented on src/tapedfunction.jl
> +        if isa(line, Core.NewvarNode)
Maybe, it will be many arguments for the would-be separated functions. This if/else branches-hell is clearer to me than separated functions while I was writing it. But for reading, separated functions may be clearer?

Let's see what other guys will say :)

2022-02-25 08:00 UTC, rikhuijzer commented on src/tapedfunction.jl
> +        if isa(line, Core.NewvarNode)
> But for reading, separated functions may be clearer?

Also for performance and extensibility. I understand that it's easier while writing and I'm okay with rewriting it to multiple functions in a separate PR

2022-02-25 08:51 UTC, KDr2 commented
I find that as `__new__` is now a generated function, we don't need to specialize the execution of `Instruction{typeof(__new__)}` any more.

This can be back ported to 0.7.x.

2022-02-25 08:58 UTC, KDr2 commented
Finally, all `Turing.jl` tests passed, let's wait for the CI task. 🎉

2022-02-25 10:10 UTC, devmotion commented on Project.toml
> +CodeInfoTools = "bc773b8a-8374-437a-b9f2-0e9785855863"
Can you add a compat entry for it?

2022-02-25 10:37 UTC, KDr2 commented on src/tapedfunction.jl
> +        if isa(line, Core.NewvarNode)
I am doing this now, will commit it by tomorrow's end.

2022-02-25 10:38 UTC, KDr2 commented on Project.toml
> +CodeInfoTools = "bc773b8a-8374-437a-b9f2-0e9785855863"
Sure, is this correct?
```diff
 [compat]
+CodeInfoTools = "0.3.4"
 LRUCache = "1.3"
 MacroTools = "0.5"
 julia = "1.7"

```

2022-02-25 11:11 UTC, rikhuijzer approved these changes
There are some minor details regarding the compat entry still and it would be good to do some benchmarks with the current implementation but to me this PR looks like an improvement, so I'll approve.

Would be good to wait on a double check from Hong and David

2022-02-25 11:14 UTC, devmotion commented on Project.toml
> +CodeInfoTools = "bc773b8a-8374-437a-b9f2-0e9785855863"
I didn't keep track of which version is sufficient but it seems tests pass with 0.3.4 so it looks good.

2022-02-25 11:22 UTC, KDr2 commented on src/tapedfunction.jl
> +        if isa(line, Core.NewvarNode)
It's easier than I thought, I just added a new commit to resolve this.

2022-02-25 11:29 UTC, KDr2 commented
> Would be good to wait on a double check from Hong and David

Hope I can have a good sleep tonight 🤣

2022-02-26 09:10 UTC, devmotion commented on src/tapedfunction.jl
> +    get!(boxes, var, Box{Any}(var, nothing))
Not sure how much it helps but one can avoid constructing the default value in every call:

```suggestion
    get!(boxes, var) do
        return Box{Any}(var, nothing)
    end
```

2022-02-26 09:12 UTC, devmotion commented on src/tapedfunction.jl
> +kind(e::Expr) = Val(e.head)
This can't be inferred - it is necessary to use `Val` here?

2022-02-26 09:14 UTC, devmotion commented on src/tapedfunction.jl
> +        tuple((Box{Any}(nothing) for _ in 1:taped.arity)...),
Can't be inferred either (since arity is not known at compile time) but avoids splatting:
```suggestion
        ntuple(_ -> Box{Any}(nothing), taped.arity),
```

2022-02-26 09:15 UTC, devmotion commented on src/tapedfunction.jl
> +    (; taped, ir, _box) = builder
This requires Julia 1.7. Fine in this PR but has to rewritten when support for Julia 1.6 is added.

2022-02-26 09:16 UTC, devmotion commented on src/tapedfunction.jl
> +    (; taped, ir, _box) = builder
Same in other functions below, of course.

2022-02-26 09:20 UTC, devmotion commented on src/tapedfunction.jl
> +        tuple((Box{Any}(nothing) for _ in 1:on_tape.arity)...),
```suggestion
        ntuple(_ -> Box{Any}(nothing), on_tape.arity),
```

2022-02-26 10:57 UTC, KDr2 commented on src/tapedfunction.jl
> +            ir = code_inferred(tf.func, args_type...)
No, `Tuple{types...}` works, but `args_type` is `::Tuple{<:DataType...}`

2022-02-26 11:13 UTC, KDr2 commented on src/tapedfunction.jl
> +kind(e::Expr) = Val(e.head)
Only calls with `Expr` are dispatched on `Val` now :)

2022-02-26 14:48 UTC, rikhuijzer commented
> How about letting Libtask v0.7.x (an LTS version as well?) keep using IRTools.jl and letting Julia prior to v1.7 use that version.

I think it’s a massive technical burden to maintain two versions in parallel

2022-02-26 15:31 UTC, devmotion commented
Yes, and in particular versions that are so different. E.g., in SpecialFunctions we backport all bug fixes to SpecialFunctions 1 to ensure that they also reach packages that have not updated their compat entry (since SpecialFunctions is such a core package and so many other packages depend on it), and that's easy since the breaking change in SpecialFunctions 2.0.0 was only the removal of the type piracy `factorial(::Number)`. However, if Libtask 0.7 depends on IRTools and 0.8 on CodeInfoTools, then I assume it will be much more difficult to backport bug fixes  and import performance improvements.

2022-02-26 15:36 UTC, devmotion commented
Is there a specific reason why it is difficult to support 1.6 but 1.8 works fine even though the CodeInfo is different from the one in 1.7 in both cases? In any case, I think it's fine to add support for 1.6 in a follow-up PR - but I also think it would be good to properly support, and hence also publish updates for, the LTS version.

2022-02-26 21:16 UTC, yebai commented
> Is there a specific reason why it is difficult to support 1.6 but 1.8 works fine even though the CodeInfo is different from the one in 1.7 in both cases? 

There is a major compiler refactoring between 1.6 and 1.7. The `CodeInfo` data structures are quite similar for 1.7 and 1.8. 

> In any case, I think it's fine to add support for 1.6 in a follow-up PR - but I also think it would be good to properly support, and hence also publish updates for, the LTS version.

The old `Libtask` mechanism does support Julia 1.6 very well. The new tape-based mechanism is introduced for Julia 1.7. It is (partially) motivated by the high maintenance burden of `Libtask` for new Julia releases. It might not add too much value by backporting the new mechanism for previous Julia releases, since the old implementation works quite well.

2022-02-26 21:36 UTC, devmotion reviewed
I think we should not even use `Val` for the `Expr` case. Unrelated of the `Expr` case, I think it is more natural to pass `ir`, `taped`, and `boxes` (not `_box`) as arguments to a function instead of constructing a callable. It seems there are also some undefined variables, so it seems not all functions are tested?

2022-02-26 21:36 UTC, devmotion commented on src/tapedfunction.jl
>      _box = (x) -> arg_boxer(x, boxes)
See suggestion below:
```suggestion
```

2022-02-26 21:36 UTC, devmotion commented on src/tapedfunction.jl
> +        builder(Core.SSAValue(idx), line)
I think a simpler design would be
```suggestion
    for (idx, line) in enumerate(ir.code)
        push!(taped, _instruction(Core.SSAValue(idx), _unbox(line), taped, ir, boxes))
```
since then you could remove the `InstructionBuilder`, avoid the unpacking in every function, and could remove the `push!` in all functions.

Additionally, one would define
```julia
_unbox(line) = line
_unbox(line::Core.Const) = line.val
```

2022-02-26 21:36 UTC, devmotion commented on src/tapedfunction.jl
> +end
```suggestion
function _instruction(@nospecialize(::IRVar), line::Core.GotoNode, taped::Taped, ::Core.CodeInfo, @nospecialize(boxes))
    cond = Box{Any}(false)
    return GotoInstruction(cond, line.label + 1, taped)
end
```

2022-02-26 21:36 UTC, devmotion commented on src/tapedfunction.jl
> +end
This will throw an error anyways:
```suggestion
```

2022-02-26 21:48 UTC, yebai requested changes
Thanks, @KDr2 - excellent work. I have some minor comments below, mostly about clarity.

2022-02-26 21:48 UTC, yebai commented on src/tapedfunction.jl
> +        builder(Core.SSAValue(idx), line)
The API is a bit confusing. Maybe consider something more explicit, e.g. 
```julia
  # builder = InstructionBuilder(taped, ir, _box)
  translate!(builder, Core.SSAValue(idx), line)
```

2022-02-26 21:48 UTC, yebai commented on src/tapedfunction.jl
>      _box = (x) -> arg_boxer(x, boxes)
Maybe consider adding the `_fn` suffix to indicate that this is a function? 
```suggestion
    _box_fn = (x) -> arg_boxer(x, boxes)
```

Alternative, we can also introduce a new type, and turn `boxes` into a callable object, e.g. 

```julia
_box = (x) -> arg_boxer(x, boxes)

# becomes 
box_fn(x) 
```

where `box_fn` is a struct that stores the current `boxes` dictionary.

2022-02-26 21:48 UTC, yebai commented on src/tapedfunction.jl
> +    end
Maybe consider simplifying this into: 
```suggestion
    return get(all_boxes, box_id, Box{Any}(nothing))
```

2022-02-26 21:48 UTC, yebai commented on src/tapedfunction.jl
>      end
Maybe consider simplifying this into 
```suggestion
    get!(boxes, var, Box{Any}(var, nothing))
```

2022-02-26 23:47 UTC, KDr2 commented on src/tapedfunction.jl
> +end
But printing out more information on error is much useful to fix it. Without this, we only get a no-method matched error.

2022-02-26 23:52 UTC, KDr2 commented on src/tapedfunction.jl
> +
I prefer not to pass so many arguments here and there, that makes long function call expressions. If there are some arguments that are all the same in a bunch of function calls, it is natural to capsulate them into a context.

2022-02-26 23:53 UTC, KDr2 commented on src/tapedfunction.jl
> +end
It's defined here: https://github.com/TuringLang/Libtask.jl/pull/126/files#diff-32dbddadf7a543bf11f421085d2833eaed85ae8599084d725af862eccd8dae2fR83

2022-02-26 23:57 UTC, KDr2 commented on src/tapedfunction.jl
> +arg_boxer(var, boxes::Dict{Symbol, Box{<:Any}}) = var
This is used for literal constants like `1`, `"a-string"`.

2022-02-27 00:05 UTC, KDr2 commented on src/tapedfunction.jl
>      end
@devmotion said `get!(boxes, var, Box{Any}(var, nothing))` will call `Box{Any}(var, nothing)` whether `haskey(boxes, var)` or not, and the function version will avoid some unnecessary call. I think he is right.

2022-02-27 00:06 UTC, KDr2 commented
> In addition, the function names `arg_boxer` and `args_initializer` are a bit misleading.

I renamed `arg_boxer` to `var_boxer`.

2022-02-27 00:08 UTC, devmotion commented on src/tapedfunction.jl
> +end
Constant propagation helps a lot:
```julia
julia> function f(expr::Expr)
           head = expr.head
           if head === :new
               return "hello"
           elseif head === :call
               return "world"
           elseif head === :(=)
               return "equals"
           elseif head === :(+)
               return "sum"
           elseif head === :(-)
               return "minus"
           elseif head === :(*)
               return "times"
           elseif head === :(/)
               return "div"
           else
               error("function not defined for head: ", head)
           end
       end
f (generic function with 1 method)

julia> g(expr::Expr) = g(expr, Val(expr.head))
g (generic function with 1 method)

julia> g(::Expr, ::Val{:new}) = "hello"
g (generic function with 2 methods)

julia> g(::Expr, ::Val{:call}) = "world"
g (generic function with 3 methods)

julia> g(::Expr, ::Val{:(=)}) = "equals"
g (generic function with 4 methods)

julia> g(::Expr, ::Val{:(+)}) = "sum"
g (generic function with 5 methods)

julia> g(::Expr, ::Val{:(-)}) = "minus"
g (generic function with 6 methods)

julia> g(::Expr, ::Val{:(*)}) = "times"
g (generic function with 7 methods)

julia> g(::Expr, ::Val{:(/)}) = "div"
g (generic function with 8 methods)

julia> using BenchmarkTools

julia> @btime f($(:(x * y)));
  4.194 ns (0 allocations: 0 bytes)

julia> @btime g($(:(x * y)));
  174.694 ns (0 allocations: 0 bytes)
```
See also: https://discourse.julialang.org/t/ann-valsplit-jl-compile-away-dynamic-dispatch-on-val-typed-arguments/77096

2022-02-27 00:10 UTC, devmotion commented on src/tapedfunction.jl
> +end
True. It would better to throw an error then and not only print an error message though.

2022-02-27 00:15 UTC, devmotion commented on src/tapedfunction.jl
> +end
Ah I see. Then the suggestion is
```suggestion
function _instruction(var::IRVar, line::GlobalRef, taped::Taped, ::Core.CodeInfo, boxes)
    return Instruction(val, (line,), arg_boxer(var, boxes), taped)
end
```

2022-02-27 00:16 UTC, devmotion commented on src/tapedfunction.jl
> +
I think the mental overhead of the `InstructionBuilder` outweighs the slightly shorter function signatures. The function is also only called in one place, so there are not many lengthy calls.

An additional advantage of passing the arguments is that you can mark a subset of them with `@nospecialize` to avoid specialization on them if they are not used in the function body.

2022-02-27 00:18 UTC, devmotion commented on src/tapedfunction.jl
> +
In any case it seems simpler and easier to read if we
- only return the instruction and `push!` inside the for loop
- pass `boxes` around instead of a `_box` closure

2022-02-27 01:36 UTC, KDr2 commented on src/tapedfunction.jl
> +
- [x] only return the instruction and push! inside the for loop
- [x] pass boxes around instead of a _box closure

But the first function signature below is too long for me, let's keep the builder for now...

```
function _instruction(taped::Taped, ir::Core.CodeInfo, boxes::Dict{Symbol, Box{:<Any}}, var::IRVar, line::Core.NewvarNode)
function (builder::InstructionBuilder)(var::IRVar, line::Core.NewvarNode)
```

2022-03-02 21:39 UTC, merged