Trying some other optimizations beside type-infer
TuringLang/Libtask.jl pull request #130
Opened 2022-03-05 00:08 UTC by KDr2

2022-03-05 02:58 UTC, KDr2 commented
```
@testset "Turing" begin
    @time include("inference/AdvancedSMC.jl")
    @time include("inference/gibbs.jl")
    @time include("contrib/inference/sghmc.jl")
    @time include("stdlib/RandomMeasures.jl")
end
```

Branch master:

```
 34.395940 seconds (82.78 M allocations: 5.174 GiB, 4.03% gc time, 95.12% compilation time)
285.165249 seconds (834.03 M allocations: 67.579 GiB, 3.62% gc time, 25.78% compilation time)
 11.141108 seconds (38.60 M allocations: 2.341 GiB, 4.64% gc time, 98.42% compilation time)
  7.159114 seconds (16.94 M allocations: 1.029 GiB, 4.85% gc time, 70.14% compilation time)
```

Branch no-type-opt:
```
 39.743907 seconds (89.76 M allocations: 5.518 GiB, 3.81% gc time, 95.43% compilation time)
299.946079 seconds (831.72 M allocations: 67.493 GiB, 3.45% gc time, 24.85% compilation time)
 11.235855 seconds (38.59 M allocations: 2.341 GiB, 4.98% gc time, 97.71% compilation time)
  9.119536 seconds (26.03 M allocations: 1.275 GiB, 4.52% gc time, 75.07% compilation time)
```

It becomes slower... 😢

2022-03-05 03:16 UTC, KDr2 commented
First commit(5ac43d4) on Branch no-type-opt:
```
 34.459184 seconds (81.37 M allocations: 5.088 GiB, 3.99% gc time, 94.95% compilation time)
302.663785 seconds (553.19 M allocations: 59.879 GiB, 3.18% gc time, 23.32% compilation time)
 10.996351 seconds (38.60 M allocations: 2.341 GiB, 5.07% gc time, 98.22% compilation time)
  7.437808 seconds (15.85 M allocations: 1012.160 MiB, 4.32% gc time, 69.07% compilation time)
```

2022-03-05 04:15 UTC, KDr2 commented
Second commit(cce6cb3) on Branch no-type-opt:
```
 34.994963 seconds (82.41 M allocations: 5.142 GiB, 4.03% gc time, 95.08% compilation time)
300.684379 seconds (615.39 M allocations: 62.235 GiB, 3.44% gc time, 23.27% compilation time)
 10.994031 seconds (38.60 M allocations: 2.341 GiB, 4.99% gc time, 98.45% compilation time)
  7.422173 seconds (17.95 M allocations: 1.065 GiB, 4.46% gc time, 69.01% compilation time)
```

2022-03-05 05:02 UTC, KDr2 commented
> First commit([5ac43d4](https://github.com/TuringLang/Libtask.jl/commit/5ac43d4515343832b16ab00a41953cd9a161d1da)) on Branch no-type-opt:

This commit has the least memory allocation, but it doesn't save much time cost.

2022-03-05 08:03 UTC, rikhuijzer commented
> > First commit([5ac43d4](https://github.com/TuringLang/Libtask.jl/commit/5ac43d4515343832b16ab00a41953cd9a161d1da)) on Branch no-type-opt:
> 
> This commit has the least memory allocation, but it doesn't save much time cost.

Could be that your computer was more busy during the one run versus the other. What you can do to dive deeper into why things are going faster or slower is to put `@time` things at some places in the codebase. As far as I can tell, it's difficult to see these instruction constructors as stand-alone, so then running larger parts with a `@time` does help sometimes.

2022-03-05 08:13 UTC, rikhuijzer reviewed
I don't understand everything. Some suggestions.

Good news about the benchmarking: https://github.com/TuringLang/Turing.jl/pull/1787 is merged, so we can now see the allocations in the integration test.

2022-03-05 08:13 UTC, rikhuijzer commented on src/tapedfunction.jl
>  mutable struct TapedFunction{F}
```suggestion
mutable struct TapedFunction{F,T}
```

2022-03-05 08:13 UTC, rikhuijzer commented on src/tapedfunction.jl
> +    retval::TypedVar
```suggestion
    retval::TypedVar{T}
```
This makes `retval` a concrete type again which avoids dynamic dispatch. The original `retval::Symbol` is more performant.

2022-03-05 08:13 UTC, rikhuijzer commented on src/tapedfunction.jl
> +end
```suggestion
function bind_var!(var::T, bindings::Dict{Symbol, Any}, ir::Core.CodeInfo) where {T} # for literal constants
    id = gensym()
    bindings[id] = var
    return TypedVar{T}(id)
end
```

2022-03-05 08:44 UTC, devmotion commented on src/tapedfunction.jl
> +end
Is there a specific reason for the static parameter? The general style guide suggests using them only if necessary: https://docs.julialang.org/en/v1/manual/style-guide/index.html#Don't-use-unnecessary-static-parameters

2022-03-05 09:15 UTC, KDr2 commented on src/tapedfunction.jl
> +end
You mean `T` in `TypedVar{T}`? The idea is, every var is a Symbol, but we don't know its type, so when executing the instruction, `input= _look_up(var_name) ;instr.func(input)`, the type of `input` is unknown. Here I try to change a var from a symbol to a `TypedVar{T}` in which `T` is its type and `id` is its name. So I expect with `input = _look_up(typedvar)::T` the compiler will know the input's type. I am not really sure if this helps, from the benchmark result I should see it doesn't help.

2022-03-05 09:45 UTC, rikhuijzer commented on src/tapedfunction.jl
> +end
Ah okay so my suggestion is wrong @devmotion? Julia will dispatch on `var` anyway and then `typeof(var)` will be inlined. I'll resolve this conversation then.

2022-03-08 09:16 UTC, yebai commented on src/tapedfunction.jl
> +_lookup(tf::TapedFunction, v::TypedVar{T}) where T = tf.bindings[v.id]::T
@KDr2 this function is probably not type-stable, despite the type assertion. The reason is that type assertion does not help with type inference (i.e. at compile time, we can't infer type of `tf.bindings[v.id]`). But rather, type assertion check the type of `tf.bindings[v.id]` at runtime, and throw an error if type constraint is violated. It should be possible to check this with a simplified example. This would also explain why the performance does not improve much with this PR.

2022-03-08 09:18 UTC, yebai commented on src/tapedfunction.jl
> +_lookup(tf::TapedFunction, v::TypedVar{T}) where T = tf.bindings[v.id]::T
See e.g. https://docs.julialang.org/en/v1/manual/performance-tips/#Annotate-values-taken-from-untyped-locations

> Type annotation will not enhance (and can actually hinder) performance if the type is abstract, or constructed at run-time.

2022-03-08 11:52 UTC, rikhuijzer commented on src/tapedfunction.jl
> +    if Base.JLOptions().code_coverage != 0 &&
What does this do?

2022-03-08 12:29 UTC, KDr2 commented on src/tapedfunction.jl
> +    if Base.JLOptions().code_coverage != 0 &&
See https://github.com/JuliaCompilerPlugins/CodeInfoTools.jl/issues/18, but I found this function doesn't fix it in all cases, I will revert or fix it soon...

2022-03-16 02:02 UTC, KDr2 commented on src/tapedfunction.jl
> +    end
@yebai here if I use `FunctionWrapper` (the commented lines), I will get many errors related to types and compilers.

Maybe `FunctionWrapper` has some glitches on Julia 1.7.

2022-03-17 09:07 UTC, yebai commented on src/tapedfunction.jl
> +mutable struct TypedFunction{OT, IT<:Tuple}
```suggestion
struct TypedFunction{OT, IT<:Tuple}
```

2022-03-17 09:07 UTC, yebai commented on src/tapedfunction.jl
> +    retval::OT
```suggestion
    retval::Ref{OT}
```

2022-03-17 09:28 UTC, yebai commented on src/tapedfunction.jl
> +_inner_setter(tf::TapedFunction, v::Symbol, c) = tf.bindings[v] = c
Maybe avoid specialising in types of `c` to reduce compilation time.

2022-03-17 09:41 UTC, yebai commented
@KDr2 Maybe we should introduce a few benchmark examples that do not depend on Turing. It allows us to better understand the performance bottleneck -- the Turing integration tests are helpful, but it involves many other parts, which make the runtime numbers hard to analyse.

2022-03-17 09:44 UTC, yebai commented on src/tapedfunction.jl
>          inputs = map(x -> val(_lookup(tf, x)), instr.input)
we should replace all `_lookup` and `_update_var!` calls with `box.getter`/`box.setter` in instructions.

2022-03-17 11:02 UTC, KDr2 commented on src/tapedfunction.jl
>          inputs = map(x -> val(_lookup(tf, x)), instr.input)
I keep `_lookup` because `Instruction.func` may be or may not be a `Box`. And, sometimes we also need to update a variable with a symbol but not a box, e.g., while we are initializing the arguments.

2022-03-17 17:17 UTC, yebai commented on src/tapedfunction.jl
>          inputs = map(x -> val(_lookup(tf, x)), instr.input)
ok, that makes sense.

2022-03-17 17:28 UTC, yebai reviewed
thanks, @KDr2  - it looks good to me. I left some minor comments below. 

I think we still need some benchmarks before merging. We need to ensure each `Instruction` in a `TapedFunction` is type-sable, if the original function `f` underlying `TapedFunction` is type stabe.

2022-03-17 17:28 UTC, yebai commented on src/tapedfunction.jl
> +    unified_tape::Vector{FunctionWrapper{Nothing, Tuple{TapedFunction}}}
Maybe merge this `unified_tape` with `tape` by using a parametric type for `tape::T`. Then we can create a `compile(TapedFunction)` API to convert TapedFunctions from `RawTape` to `Vector{FunctionWrapper{Nothing, Tuple{TapedFunction}}}`.

2022-03-17 17:28 UTC, yebai commented on src/tapedfunction.jl
> +function unify!(tf::TapedFunction)
```suggestion
function compile(tf::TapedFunction)
```

2022-03-17 19:44 UTC, devmotion requested changes
My main suggestion is to use `Base.RefValue` instead of `Ref`.

It is unclear to me if/how this affects performance. It would be good to perform some benchmarks (or (re-)post them, if they exist - I assumed the comments above are outdated).

2022-03-17 19:44 UTC, devmotion commented on src/tapedfunction.jl
> +    retval::Ref{OT}
This should be changed to
```suggestion
    retval::Base.RefValue{OT}
```
since
```julia
julia> isconcretetype(Ref{Float64})
false

julia> isconcretetype(Base.RefValue{Float64})
true
```
This makes a huge difference in practice, e.g.
```julia
julia> using BenchmarkTools

julia> struct A{T}
           x::Ref{T}
       end

julia> struct B{T}
           x::Base.RefValue{T}
       end

julia> function f(x::Union{A{T},B{T}}) where {T}
           s = zero(T)
           for _ in 1:10_000
               s += x.x[]
           end
           s
       end
f (generic function with 1 method)

julia> @btime f($(A(Ref(1.0))));
  130.273 μs (20000 allocations: 312.50 KiB)

julia> @btime f($(B(Ref(1.0))));
  8.492 μs (0 allocations: 0 bytes)
```

2022-03-17 19:44 UTC, devmotion commented on src/tapedfunction.jl
> +    func::Function
I guess this abstract type is desired?

2022-03-17 19:44 UTC, devmotion commented on src/tapedfunction.jl
> +    return f.retval[]
A bit simpler, without accessing `retval` twice:
```suggestion
    f.reval[] = OT === Nothing ? nothing : output
```

2022-03-17 22:37 UTC, KDr2 commented on src/tapedfunction.jl
> +    func::Function
I didn't put it into type parameters due to that I want `TypedFunction` and `FunctionWrapper` to have the same type signature. Maybe we can ignore the usage of `FunctionWrapper` here because it is problematic and we may not use it anymore?

2022-03-18 13:48 UTC, merged