use memory layout info to copy task
TuringLang/Libtask.jl pull request #89
Opened 2021-06-18 06:13 UTC by KDr2

2021-06-18 15:18 UTC, yebai requested changes
thanks, @KDr2 - looks good! I left some minor comments below. 

Also, I would suggest that we keep the `memlayout.cpp` file under `Libtask_jll`. Assuming that we need to re-run `memlayout` inside a Github workflow,  in order to get the member layout for a new Julia release, we can import `Libtask_jll`. However, this step can be done after the code becomes more mature to avoid frequent changes to `Libtask_jll` during the development phase.

2021-06-18 15:18 UTC, yebai commented on src/ctask.jl
> +        ccall((:jl_setfield_int32_t, libtask_julia),
Maybe consider rewrapping the repetative `getfield/setfield` code block into a `setfield/getfield` function, e.g. 

```julia
function setfield(t, fieldname, value)
        ccall((:jl_setfield_int32_t, libtask_julia),
              Any, (Any, Csize_t, Int32),
              t, TASK_OFFSETS[:copy_stack], 1)
end
```

2021-06-18 15:18 UTC, yebai commented on src/ctask.jl
> +    haskey(TASK_OFFSETS, :exception) && ccall(
Similarly, please consider replacing the `ccall` code block with a more readable `setfield/getfield` function.

2021-06-22 02:07 UTC, KDr2 commented on src/ctask.jl
> +    haskey(TASK_OFFSETS, :exception) && ccall(
Done.

2021-06-24 05:51 UTC, KDr2 commented
Now, it's ready to be reviewed and merged.

2021-06-24 15:06 UTC, yebai approved these changes
Looks good to me overall - one minor comment: maybe create a subfolder in `workflows` for `tasklayout` and store the Julia script and cpp source file inside `tasklayout`? 

@devmotion This PR is attempting to crate a more maintainable version of `Libtask` by doing most of the task struct manipulation operations on the Julia side, and minimise the operations on the C side (i.e. in `Libtask_jll`). The solution here is not yet perfect, but operational, and already more generic than the current mechanism (e.g. it works correctly on Julia `v.1.5.4` and `v1.5.3`). Can you take a look and see whether you have any comments?

2021-06-25 04:11 UTC, KDr2 commented
> maybe create a subfolder in `workflows` for `tasklayout` and store the Julia script and cpp source file inside `tasklayout`?

Done.

2021-06-26 12:20 UTC, merged